import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { PageFooter, PageHeader } from "@/components/layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.className,
          "grid grid-rows-[auto_1fr_auto] min-h-screen"
        )}
      >
        <PageHeader />
        <div className="grid grid-cols-layout [&>*]:col-start-2">
          {children}
        </div>
        <PageFooter />
      </body>
    </html>
  );
}
